# Used by label action

# Add 'repo' label to any root file changes
repo:
  - ./*

workflow:
  - .github

poi:
  - apis/poi

trips:
  - apis/trips

user-java:
  - apis/user-java

userprofile:
  - apis/userprofile

  
