name: CreateDependabotIssue
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
    types: [ opened, reopened]

jobs:
  issue:
      runs-on: ubuntu-latest
      steps:

        - name: Open issue if Dependabot PR
          if: ${{ github.event.pull_request.user.login }} == "dependabot[bot]"
          run: |
            echo "this pr was created by dependabot"