name: CreateDependabotIssue
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
    types: [ opened, reopened]

jobs:
  issue:
      runs-on: ubuntu-latest
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      steps:
        - name: Open issue if Dependabot PR
          if: github.event.pull_request.user.login  == 'dependabot[bot]'
          run: |
            title="Dependabot PR ${{ github.event.pull_request.title }} opened"
            body="Dependabot has opened PR #${{ github.event.pull_request.number }}
            Link: ${{event.pull_request.labels.url}}"
            gh issue create --title "$title" --body "$body"    
