
name: Label

on: [pull_request]
  
jobs:
  label:

    runs-on: ubuntu-latest

    steps:
    # To use this workflow, you will need to set up a .github/labeler.yml
    # file with configuration.  For more information, see:
    # https://github.com/actions/labeler
    - name: Label PR
      uses: actions/labeler@v3
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        

