name: dumppr


on:
  workflow_dispatch:
  pull_request:
    branches: [ master ]

jobs:
  showinfo:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      # - name: Dump GitHub pr content
      #   env:
      #     GITHUB_PR: ${{ toJson(github) }}
      #   run: echo "$GITHUB_PR"

