name: dumppr


on:
  workflow_dispatch:
#  pull_request:
#    branches: [ master ]

jobs:
  showinfo:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          event_name: ${{github.event.pull_request.labels.name}}
          event_who: ${{github.event.pull_request.user.login}}
        run: |
          # echo "$GITHUB_CONTEXT"
          echo "$event_name"
          echo "$event_who"

      # - name: Dump GitHub pr content
      #   env:
      #     GITHUB_PR: ${{ toJson(github) }}
      #   run: echo "$GITHUB_PR"

