name: build-trips

env:
  apiname: trips
  repo: devopsoh/api-trips
  acrreg: openhack8pm8c3y5acr
  acrsite: openhack8pm8c3y5acr.azurecr.io
  tenant: 3ba0d033-7360-4927-8b0d-337841610e82

on:
  workflow_dispatch:
  push:
    branches: [ '*' ]
    paths: 
      - apis/trips/**  
      - .github/workflows/trips-build.yml
  pull_request:
    branches: [ master ]
    paths: 
      - apis/trips/**
      - .github/workflows/trips-build.yml



# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Configures Docker actions to use buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-${{env.apiname}}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{env.apiname}}-


      # - name: Login to GitHub Container Registry
      #   uses: docker/login-action@v1
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.repository_owner }}
      #     password: ${{ secrets.CR_PAT }}

      - name: Login to Azure Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{env.acrsite}}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}


      # - uses: azure/login@v1
      #   name: Azure Login
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}

      # - name: Log into ACR
      #   uses: azure/CLI@v1
      #   with:
      #     #azcliversion: 2.0.72
      #     inlineScript: |
      #       tj=$(az acr login -n ${{env.acrreg}} -t)
      #       token=$(echo $tj|jq -r .token)



# look at https://github.com/metcalfc/docker-action-examples/blob/main/.github/workflows/pr-ci.yml


      - name: Build trips app and run test
        id: userprofile_docker_test
        uses: docker/build-push-action@v2
        with:
          load: true
          # push: true
          tags: |
            ${{env.acrsite}}/${{ github.repository_owner }}/${{env.repo}}-test:${{ github.run_number }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          file: apis/${{env.apiname}}/Dockerfile
          context: apis/${{env.apiname}}
          target: test
          # old tags:
          # ghcr.io/${{ github.repository_owner }}/oh${{env.apiname}}:${{ github.run_number }}
          # ghcr.io/${{ github.repository_owner }}/oh${{env.apiname}}:latest

      - name: create issue if build & test failed
        if: failure()
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          title="${{ env.build_name }} Workflow ${{ github.run_number }} Failed! "
          body="${{ env.build_name }} Worflow Failure \
          Build Number: ${{ github.run_number }} \
          Build Log: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }} \
          SHA: [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }})"
          gh issue create --title "$title" --body "$body"

      - name: Build trips app and push
        id: userprofile_docker_buildpush
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{env.acrsite}}/${{ github.repository_owner }}/${{env.repo}}:${{ github.run_number }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          file: apis/${{env.apiname}}/Dockerfile
          context: apis/${{env.apiname}}
          target: gorun
          # old tags:
          # ghcr.io/${{ github.repository_owner }}/oh${{env.apiname}}:${{ github.run_number }}
          # ghcr.io/${{ github.repository_owner }}/oh${{env.apiname}}:latest




