name: build-userprofile

on:
  workflow_dispatch:
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Configures Docker actions to use buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1


      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

# look at https://github.com/metcalfc/docker-action-examples/blob/main/.github/workflows/pr-ci.yml

      - run: |
          echo ${{ github.run_number }}
          echo ${{ github.run_id }}


#### Need to add tag version!!!!
      - name: Build and push userprofile app
        id: userprofile_docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/ohuserprofile:${{ github.run_number }}
            ghcr.io/${{ github.repository_owner }}/ohuserprofile:latest
          #cache-from: type=local,src=/tmp/.buildx-cache
          #cache-to: type=local,dest=/tmp/.buildx-cache
          file: apis/userprofile/Dockerfile
          context: apis/userprofile